# Generated by Django 4.0.3 on 2022-04-10 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('hint_used', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SudokuCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('square', models.IntegerField()),
                ('cell_id', models.CharField(max_length=2)),
                ('possibilities', models.CharField(default='123456789', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SudokuBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_string', models.CharField(max_length=82)),
                ('cells', models.ManyToManyField(related_name='boards', to='app.sudokucell')),
                ('steps', models.ManyToManyField(related_name='boards', to='app.solutionstep')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='solutionstep',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.sudokucell'),
        ),
    ]
