# Generated by Django 4.0.3 on 2022-04-14 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SudokuBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.JSONField()),
                ('board_string', models.CharField(max_length=82)),
                ('solution_string', models.CharField(max_length=82)),
                ('hint_used', models.BooleanField(default=False)),
                ('started_datetime', models.DateTimeField(auto_now=True)),
                ('finished_datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
